# Generated by Django 3.2.11 on 2022-01-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_company_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(max_length=250),
        ),
    ]
